const data = {
    products: [
      {
        _id: '1',
        name: 'Hoa 1',
        category: 'Shirts',
        image: '/images/p-3.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 2.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Hoa 2',
        category: 'Shirts',
        image: '/images/p-1.jpg',
        price: 100,
        countInStock: 20,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Hoa 3',
        category: 'Shirts',
        image: '/images/p-2.jpg',
        price: 220,
        countInStock: 0,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Hoa 1',
        category: 'Pants',
        image: '/images/p-1.jpg',
        price: 78,
        countInStock: 15,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Hoa 2',
        category: 'Pants',
        image: '/images/p-2.jpg',
        price: 65,
        countInStock: 5,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Hoa 3',
        category: 'Pants',
        image: '/images/p-3.jpg',
        price: 139,
        countInStock: 12,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;